### PR TITLE
any2jd: raise error if object cannot be converted

### PR DESCRIPTION
**Pull request by FreyJo**
I found this useful when trying to dump a nested structure with objects that need to be converted carefully.

### CODE REVIEW

**Comment by fangq** [comment]
@FreyJo, thanks for your patch - can you post a small reproducer code so that I can recreate the error? I am curious what object that `getByteStreamFromArray()` in matlab fails to serialize.

**Comment by FreyJo** [comment]
We are using `jsonlab` in [acados](https://github.com/acados/acados/) to dump the problem formulation of an optimization problem to a json file and then perform code generation.
E.g. if there are CasADi expressions in the struct to be dumped, it fails.
Also we dump objects of types that we define in our Matlab interface which need to be converted to structs before dumping them via `jsonlab`.
So this change was useful when changing our interface, as currently done in https://github.com/acados/acados/pull/1193

**Comment by fangq** [comment]
I see. can you confirm if you had used [miss_hit](https://misshit.org/) `mh_style --fix .` inside jsonlab root folder to format the added lines? currently, the code is formatted with mh_style 0.9.35-dev on a Ubuntu 18.04/20.04 linux box. ideally, if there is any format correction, it should be only in the updated section.

**Comment by fangq** [comment]
thanks, merged, the format looks fine.

**Pull request merged**
