### PR TITLE
Feature/enum support

### PR DESCRIPTION
**Pull request by etxealaikoion**
Hi,

I implemented the serialization of "enum" types.

Those are very small changes that you can look at directly on the code. I'm using it quite extensively and it is working properly.

Please, take a look and ask me any questions or proposals.

Regards,

Ion

### CODE REVIEW

**Comment by fangq** [comment]
thanks for sharing this patch, however, I believe the current version of savejson.m can already handle enum data types. Please test

```
classdef WeekDays
   enumeration
      Monday, Tuesday, Wednesday, Thursday, Friday
   end
end
```
```

>> today = WeekDays.Tuesday;
>> savejson(today)

ans =

    '{
     	"today": "Tuesday"
     }
     '
```

**Comment by etxealaikoion** [comment]
I'll try and let you know. Thanks for your great job!

Hau idatzi du Qianqian Fang (notifications@github.com) erabiltzaileak (2019
urr. 24, og. (23:25)):

**Comment by etxealaikoion** [comment]
I finally tested your new version, and it works perfectly for enumeration types.

Thank you and sorry about this loooong delay!

**Comment by fangq** [comment]
great!

**Pull request closed without merging**
